// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrueDope.Api.Data;

#nullable disable

namespace TrueDope.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251228231915_AddCTCAndETEMeasurements")]
    partial class AddCTCAndETEMeasurements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.AdminAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AdminUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TargetEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TargetUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.AmmoLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmmunitionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InitialQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("AmmunitionId", "LotNumber")
                        .IsUnique();

                    b.ToTable("AmmoLots");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.Ammunition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BallisticCoefficient")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("BulletType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Caliber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("CostPerRound")
                        .HasColumnType("decimal(8,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DragModel")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<decimal>("Grain")
                        .HasColumnType("decimal(6,1)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Ammunition");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.ChronoSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AmmoLotId")
                        .HasColumnType("integer");

                    b.Property<int>("AmmunitionId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AverageVelocity")
                        .HasColumnType("decimal(6,1)");

                    b.Property<decimal?>("BarrelTemperature")
                        .HasColumnType("decimal(5,1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ExtremeSpread")
                        .HasColumnType("decimal(6,1)");

                    b.Property<decimal?>("HighVelocity")
                        .HasColumnType("decimal(6,1)");

                    b.Property<decimal?>("LowVelocity")
                        .HasColumnType("decimal(6,1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("NumberOfRounds")
                        .HasColumnType("integer");

                    b.Property<int>("RangeSessionId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StandardDeviation")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AmmoLotId");

                    b.HasIndex("AmmunitionId");

                    b.HasIndex("RangeSessionId")
                        .IsUnique();

                    b.ToTable("ChronoSessions");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.DopeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AmmoLotId")
                        .HasColumnType("integer");

                    b.Property<int?>("AmmunitionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Distance")
                        .HasColumnType("integer");

                    b.Property<decimal>("ElevationMils")
                        .HasColumnType("decimal(8,3)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RangeSessionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("WindageMils")
                        .HasColumnType("decimal(8,3)");

                    b.HasKey("Id");

                    b.HasIndex("AmmoLotId");

                    b.HasIndex("AmmunitionId");

                    b.HasIndex("RangeSessionId");

                    b.HasIndex("RangeSessionId", "Distance")
                        .IsUnique();

                    b.ToTable("DopeEntries");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.GroupEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AmmoLotId")
                        .HasColumnType("integer");

                    b.Property<int?>("AmmunitionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Distance")
                        .HasColumnType("integer");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("integer");

                    b.Property<decimal?>("GroupSizeMoa")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal?>("MeanRadiusMoa")
                        .HasColumnType("decimal(6,3)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("NumberOfShots")
                        .HasColumnType("integer");

                    b.Property<int>("RangeSessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AmmoLotId");

                    b.HasIndex("AmmunitionId");

                    b.HasIndex("RangeSessionId");

                    b.ToTable("GroupEntries");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.GroupMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnnotatedImageId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BulletDiameter")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("CalibrationMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Cep50")
                        .HasColumnType("decimal(6,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ExtremeSpreadCtc")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("ExtremeSpreadEte")
                        .HasColumnType("decimal(6,4)");

                    b.Property<int>("GroupEntryId")
                        .HasColumnType("integer");

                    b.Property<string>("HolePositionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("HorizontalSpreadCtc")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("HorizontalSpreadEte")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("HorizontalStdDev")
                        .HasColumnType("decimal(6,5)");

                    b.Property<decimal?>("MeanRadius")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("MeasurementConfidence")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int?>("OriginalImageId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PoiOffsetX")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("PoiOffsetY")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("RadialStdDev")
                        .HasColumnType("decimal(6,5)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("VerticalSpreadCtc")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("VerticalSpreadEte")
                        .HasColumnType("decimal(6,4)");

                    b.Property<decimal?>("VerticalStdDev")
                        .HasColumnType("decimal(6,5)");

                    b.HasKey("Id");

                    b.HasIndex("AnnotatedImageId");

                    b.HasIndex("GroupEntryId")
                        .IsUnique();

                    b.HasIndex("OriginalImageId");

                    b.ToTable("GroupMeasurements");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int?>("GroupEntryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("RangeSessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("RifleSetupId")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupEntryId");

                    b.HasIndex("RangeSessionId");

                    b.HasIndex("RifleSetupId");

                    b.HasIndex("UserId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.RangeSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DensityAltitude")
                        .HasColumnType("decimal(7,1)");

                    b.Property<int?>("Humidity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<string>("LocationName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("Pressure")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RifleSetupId")
                        .HasColumnType("integer");

                    b.Property<int?>("SavedLocationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("SessionTime")
                        .HasColumnType("interval");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WindDirection")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WindSpeed")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("RifleSetupId");

                    b.HasIndex("SavedLocationId");

                    b.HasIndex("SessionDate");

                    b.HasIndex("UserId");

                    b.ToTable("RangeSessions");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.RifleSetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BallisticCoefficient")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal?>("BarrelLength")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("Caliber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DragModel")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("MuzzleVelocity")
                        .HasColumnType("decimal(6,1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("ScopeHeight")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("ScopeMake")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ScopeModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TwistRate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ZeroDistance")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ZeroElevationClicks")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ZeroWindageClicks")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RifleSetups");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.SavedLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Altitude")
                        .HasColumnType("decimal(7,1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavedLocations");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.SharedLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Altitude")
                        .HasColumnType("decimal(7,1)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsActive");

                    b.HasIndex("State");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("SharedLocations");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.UserPreferences", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("AdjustmentUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DistanceUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("GroupSizeMethod")
                        .HasColumnType("integer");

                    b.Property<string>("PressureUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TemperatureUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VelocityUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.VelocityReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChronoSessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShotNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Velocity")
                        .HasColumnType("decimal(6,1)");

                    b.HasKey("Id");

                    b.HasIndex("ChronoSessionId");

                    b.HasIndex("ChronoSessionId", "ShotNumber")
                        .IsUnique();

                    b.ToTable("VelocityReadings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrueDope.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.AdminAuditLog", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.User", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.AmmoLot", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.Ammunition", "Ammunition")
                        .WithMany("AmmoLots")
                        .HasForeignKey("AmmunitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrueDope.Api.Data.Entities.User", "User")
                        .WithMany("AmmoLots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ammunition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.Ammunition", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.User", "User")
                        .WithMany("Ammunition")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.ChronoSession", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.AmmoLot", "AmmoLot")
                        .WithMany("ChronoSessions")
                        .HasForeignKey("AmmoLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrueDope.Api.Data.Entities.Ammunition", "Ammunition")
                        .WithMany("ChronoSessions")
                        .HasForeignKey("AmmunitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrueDope.Api.Data.Entities.RangeSession", "RangeSession")
                        .WithOne("ChronoSession")
                        .HasForeignKey("TrueDope.Api.Data.Entities.ChronoSession", "RangeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AmmoLot");

                    b.Navigation("Ammunition");

                    b.Navigation("RangeSession");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.DopeEntry", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.AmmoLot", "AmmoLot")
                        .WithMany("DopeEntries")
                        .HasForeignKey("AmmoLotId");

                    b.HasOne("TrueDope.Api.Data.Entities.Ammunition", "Ammunition")
                        .WithMany("DopeEntries")
                        .HasForeignKey("AmmunitionId");

                    b.HasOne("TrueDope.Api.Data.Entities.RangeSession", "RangeSession")
                        .WithMany("DopeEntries")
                        .HasForeignKey("RangeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AmmoLot");

                    b.Navigation("Ammunition");

                    b.Navigation("RangeSession");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.GroupEntry", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.AmmoLot", "AmmoLot")
                        .WithMany("GroupEntries")
                        .HasForeignKey("AmmoLotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrueDope.Api.Data.Entities.Ammunition", "Ammunition")
                        .WithMany("GroupEntries")
                        .HasForeignKey("AmmunitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrueDope.Api.Data.Entities.RangeSession", "RangeSession")
                        .WithMany("GroupEntries")
                        .HasForeignKey("RangeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AmmoLot");

                    b.Navigation("Ammunition");

                    b.Navigation("RangeSession");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.GroupMeasurement", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.Image", "AnnotatedImage")
                        .WithMany()
                        .HasForeignKey("AnnotatedImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrueDope.Api.Data.Entities.GroupEntry", "GroupEntry")
                        .WithOne("Measurement")
                        .HasForeignKey("TrueDope.Api.Data.Entities.GroupMeasurement", "GroupEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrueDope.Api.Data.Entities.Image", "OriginalImage")
                        .WithMany()
                        .HasForeignKey("OriginalImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnnotatedImage");

                    b.Navigation("GroupEntry");

                    b.Navigation("OriginalImage");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.Image", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.GroupEntry", "GroupEntry")
                        .WithMany("Images")
                        .HasForeignKey("GroupEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrueDope.Api.Data.Entities.RangeSession", "RangeSession")
                        .WithMany("Images")
                        .HasForeignKey("RangeSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrueDope.Api.Data.Entities.RifleSetup", "RifleSetup")
                        .WithMany("Images")
                        .HasForeignKey("RifleSetupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrueDope.Api.Data.Entities.User", "User")
                        .WithMany("Images")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupEntry");

                    b.Navigation("RangeSession");

                    b.Navigation("RifleSetup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.RangeSession", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.RifleSetup", "RifleSetup")
                        .WithMany("RangeSessions")
                        .HasForeignKey("RifleSetupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrueDope.Api.Data.Entities.SavedLocation", "SavedLocation")
                        .WithMany("RangeSessions")
                        .HasForeignKey("SavedLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrueDope.Api.Data.Entities.User", "User")
                        .WithMany("RangeSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RifleSetup");

                    b.Navigation("SavedLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.RifleSetup", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.User", "User")
                        .WithMany("RifleSetups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.SavedLocation", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.User", "User")
                        .WithMany("SavedLocations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.SharedLocation", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.UserPreferences", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("TrueDope.Api.Data.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.VelocityReading", b =>
                {
                    b.HasOne("TrueDope.Api.Data.Entities.ChronoSession", "ChronoSession")
                        .WithMany("VelocityReadings")
                        .HasForeignKey("ChronoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChronoSession");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.AmmoLot", b =>
                {
                    b.Navigation("ChronoSessions");

                    b.Navigation("DopeEntries");

                    b.Navigation("GroupEntries");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.Ammunition", b =>
                {
                    b.Navigation("AmmoLots");

                    b.Navigation("ChronoSessions");

                    b.Navigation("DopeEntries");

                    b.Navigation("GroupEntries");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.ChronoSession", b =>
                {
                    b.Navigation("VelocityReadings");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.GroupEntry", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.RangeSession", b =>
                {
                    b.Navigation("ChronoSession");

                    b.Navigation("DopeEntries");

                    b.Navigation("GroupEntries");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.RifleSetup", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("RangeSessions");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.SavedLocation", b =>
                {
                    b.Navigation("RangeSessions");
                });

            modelBuilder.Entity("TrueDope.Api.Data.Entities.User", b =>
                {
                    b.Navigation("AmmoLots");

                    b.Navigation("Ammunition");

                    b.Navigation("Images");

                    b.Navigation("Preferences");

                    b.Navigation("RangeSessions");

                    b.Navigation("RifleSetups");

                    b.Navigation("SavedLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
